language: minimal
dist: bionic

env:
  - DEPLOY_NODE="repo.opensvc.com" DEPLOY_USER="opensvc" PRIVATE_RSA="./deploy/id_rsa_travis" ENCRYPTED_PRIVATE_RSA="${PRIVATE_RSA}.enc"

before_install:
- openssl aes-256-cbc -K $encrypted_e7f5b74d8bfb_key -iv $encrypted_e7f5b74d8bfb_iv
  -in ${ENCRYPTED_PRIVATE_RSA} -out ${PRIVATE_RSA} -d
- eval "$(ssh-agent -s)"
- chmod 600 ${PRIVATE_RSA}
- echo -e "Host ${DEPLOY_NODE}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ${PRIVATE_RSA}
- ssh -qi ${PRIVATE_RSA} ${DEPLOY_USER}@${DEPLOY_NODE} "hostname ; pwd"
- sudo apt -y install nodejs-dev node-gyp libssl1.0-dev npm
addons:
  apt:
    update: true

install:
- npm install
- npm list -g --depth=0

script:
- npm run build
- rm -rf debug
- mv dist debug
- npm config set opensvc-cluster-manager:mode production
- npm run build

after_success:
- ssh -i ${PRIVATE_RSA} ${DEPLOY_USER}@${DEPLOY_NODE} "test -d /usr/share/opensvc/html || sudo /bin/mkdir -p /usr/share/opensvc/html"
- ssh -i ${PRIVATE_RSA} ${DEPLOY_USER}@${DEPLOY_NODE} "sudo /bin/chown opensvc:opensvc /usr/share/opensvc/html"
- scp -i ${PRIVATE_RSA} ./dist/index* ${DEPLOY_USER}@${DEPLOY_NODE}:/usr/share/opensvc/html/

deploy:
  - provider: script
    script: bash deploy/deploy.sh $(jq -r '.version' package.json)
    skip_cleanup: true
    on:
      all_branches: true 
